kind: Service
apiVersion: v1
metadata:
  name: invokeclient
  labels:
    app: invokeclient
spec:
  selector:
    app: invokeclient
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invokeclient
  labels:
    app: invokeclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invokeclient
  template:
    metadata:
      labels:
        app: invokeclient
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "invokeclient"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: invokeclient
        image: nikawang.azurecr.io/dapr/dapr-client:v4
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
